version: '2'
services:
  web:
    image: 'nginx:latest'
    ports:
      - '8080:80'
    volumes:
      - './src:/src'
      - './nginx/site.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
    networks:
      - code-network
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - './src:/src'
    networks:
      - code-network
    depends_on:
      - composer
  composer:
    image: composer
    volumes:
      - './src:/app'
    command: install --no-dev
  db:
    image: postgres
    environment: []
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
networks:
  code-network:
    driver: bridge
volumes:
  pgdata: null
